# Generated by Django 4.0.6 on 2022-07-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0003_alter_task_deadline_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.ImageField(blank=True, upload_to='task_pics/', verbose_name='picture'),
        ),
    ]
